# Generated by Django 3.2.20 on 2023-11-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gymslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('slot_date', models.CharField(max_length=10, verbose_name='Event Date')),
                ('slot_time', models.CharField(max_length=10, verbose_name='Event Time')),
                ('submit', models.BooleanField()),
            ],
        ),
    ]
