# Generated by Django 3.2.16 on 2023-02-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymtrainer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
