# Generated by Django 3.2.16 on 2023-02-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gymtrainer', '0002_auto_20230201_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gymslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('submit', models.BooleanField()),
            ],
        ),
    ]
