# Generated by Django 3.2.16 on 2023-02-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtrainer', '0005_auto_20230202_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='gymtrainer.MyCLubUser'),
        ),
    ]
