# Generated by Django 3.2.16 on 2023-02-02 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymtrainer', '0008_auto_20230202_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymslot',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=120, verbose_name='Event Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='gymtrainer.MyClubUser'),
        ),
    ]
