# Generated by Django 3.2.16 on 2023-02-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtrainer', '0009_auto_20230202_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='gymtrainer.MyClubUser'),
        ),
    ]
