# Generated by Django 3.2.16 on 2023-02-02 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymtrainer', '0011_alter_event_attendees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='MyCLUbUser',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
