# Generated by Django 3.2.19 on 2023-09-01 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('gymtrainer', '0015_auto_20230202_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymslot',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gymslot', to='profiles.userprofile'),
        ),
    ]
